name: Build the documentation for the project.
run-name: Documentation

on:
  push:
    paths:
      - "**.py"
      - "**.rst"
      - "**.md"
      - .github/workflows/docu.yaml

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install dependencies"
        run: |
          pip install sphinx
          pip install sphinx-autoapi
          pip install myst-parser
          pip install furo
          pip install sphinx-copybutton

      - name: "Build documentation"
        run:
          sphinx-build -b html ./doc/source ./doc/build

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: "NukeTestingDocumentation"
          path: ./doc/build/*
          retention-days: 2
  deploy-documentation:
    runs-on: ubuntu-latest
    needs: documentation
    steps:
      - name: Download build page
        uses: actions/download-artifact@v4
        with:
          name: "NukeTestingDocumentation"
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4